<?php

return [
    [
        'type_id' => '1',
        "title" => "SpotifyWeb",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "",
        "description" => "clone of spotify",
        "image" => "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Spotify_logo_without_text.svg/2048px-Spotify_logo_without_text.svg.png",
        "technologies" => [1],
        "link_github" => "https://github.com/FeliceDArcangelo/html-css-spotifyweb",
    ],
    [
        'type_id' => '1',
        "title" => "Minefield",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-04-28",
        "last_update" => "2023-04-28",
        "collaborators" => "",
        "description" => "clone of minefield",
        "image" => "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Gnome_Mines.png/220px-Gnome_Mines.png",
        "technologies" => [1, 2],
        "link_github" => "https://github.com/FeliceDArcangelo/js-campominato-grid",
    ],
    [
        'type_id' => '1',
        "title" => "Boolzapp",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-05-15",
        "last_update" => "2023-05-15",
        "collaborators" => "",
        "description" => "clone of social",
        "image" => "https://images.sftcdn.net/images/t_app-icon-m/p/acc12314-96d1-11e6-b37d-00163ed833e7/2443124292/whatsapp-web-icon.png",
        "technologies" => [1, 2],
        "link_github" => "https://github.com/FeliceDArcangelo/vue-boolzapp",
    ],
    [
        'type_id' => '1',
        "title" => "Boolflix",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-06-3",
        "last_update" => "2023-06-3",
        "collaborators" => "",
        "description" => "clone of netflix",
        "image" => "https://img.freepik.com/free-icon/netflix_318-566093.jpg?w=360",
        "technologies" => [1, 3],
        "link_github" => "https://github.com/FeliceDArcangelo/vite-boolflix",
    ],
    [
        'type_id' => '1',
        "title" => "Designer",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-06-01",
        "collaborators" => "",
        "description" => "clone of graphic page",
        "image" => "https://leverageedublog.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2019/10/23170637/Graphic-Design-Courses.jpg",
        "technologies" => [1, 3],
        "link_github" => "https://github.com/FeliceDArcangelo/proj-html-vuejs",
    ],
    [
        'type_id' => '2',
        "title" => "Travel Agency",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Felice D'Arcangelo - Lamberto Neri - Nicola Soggiu - Giulio D'Angelo - Domenico Ferrari",
        "description" => "clone of travel agency",
        "image" => "https://a.cdn-hotels.com/gdcs/production133/d1207/7ad2d7f0-68ce-11e8-8a0f-0242ac11000c.jpg",
        "technologies" => [5],
        "link_github" => "https://github.com/FeliceDArcangelo/laravel-boolean",
    ],
    
];